#!/usr/bin/python3
import sys

with open(sys.argv[1], 'r') as fp:
    text = fp.read()

text = text \
    .replace('ΐ', 'i') \
    .replace('Α', 'a') \
    .replace('Β', 'b') \
    .replace('Γ', 'g') \
    .replace('Δ', 'd') \
    .replace('Ε', 'e') \
    .replace('Ζ', 'z') \
    .replace('Η', 'E') \
    .replace('Θ', 'th') \
    .replace('Ι', 'i') \
    .replace('Κ', 'k') \
    .replace('Λ', 'l') \
    .replace('Μ', 'm') \
    .replace('Ν', 'n') \
    .replace('Ξ', 'x') \
    .replace('Ο', 'o') \
    .replace('Π', 'p') \
    .replace('Ρ', 'r') \
    .replace('Σ', 's') \
    .replace('Τ', 't') \
    .replace('Υ', 'u') \
    .replace('Φ', 'ph') \
    .replace('Χ', 'ch') \
    .replace('Ψ', 'ps') \
    .replace('ά', 'a') \
    .replace('έ', 'e') \
    .replace('ή', 'E') \
    .replace('ί', 'i') \
    .replace('ΰ', 'u') \
    .replace('α', 'a') \
    .replace('β', 'b') \
    .replace('γ', 'g') \
    .replace('δ', 'd') \
    .replace('ε', 'e') \
    .replace('ζ', 'z') \
    .replace('η', 'E') \
    .replace('θ', 'th') \
    .replace('ι', 'i') \
    .replace('κ', 'k') \
    .replace('λ', 'l') \
    .replace('μ', 'm') \
    .replace('ν', 'n') \
    .replace('ξ', 'x') \
    .replace('ο', 'o') \
    .replace('π', 'p') \
    .replace('ρ', 'r') \
    .replace('ς', 's') \
    .replace('σ', 's') \
    .replace('τ', 't') \
    .replace('υ', 'u') \
    .replace('φ', 'ph') \
    .replace('χ', 'ch') \
    .replace('ψ', 'ps') \
    .replace('ω', 'O') \
    .replace('ϊ', 'i') \
    .replace('ϋ', 'u') \
    .replace('ό', 'o') \
    .replace('ύ', 'u') \
    .replace('ώ', 'O') \
    .replace('ἀ', 'a') \
    .replace('ἁ', 'a') \
    .replace('ἂ', 'a') \
    .replace('ἃ', 'a') \
    .replace('ἄ', 'a') \
    .replace('ἅ', 'a') \
    .replace('ἆ', 'a') \
    .replace('Ἀ', 'a') \
    .replace('Ἁ', 'a') \
    .replace('Ἃ', 'a') \
    .replace('Ἄ', 'a') \
    .replace('Ἅ', 'a') \
    .replace('Ἆ', 'a') \
    .replace('ἐ', 'e') \
    .replace('ἑ', 'e') \
    .replace('ἓ', 'e') \
    .replace('ἔ', 'e') \
    .replace('ἕ', 'e') \
    .replace('Ἐ', 'e') \
    .replace('Ἑ', 'e') \
    .replace('Ἓ', 'e') \
    .replace('Ἔ', 'e') \
    .replace('Ἕ', 'e') \
    .replace('ἠ', 'E') \
    .replace('ἡ', 'E') \
    .replace('ἢ', 'E') \
    .replace('ἣ', 'E') \
    .replace('ἤ', 'E') \
    .replace('ἥ', 'E') \
    .replace('ἦ', 'E') \
    .replace('ἧ', 'E') \
    .replace('Ἠ', 'E') \
    .replace('Ἡ', 'E') \
    .replace('Ἢ', 'E') \
    .replace('Ἤ', 'E') \
    .replace('Ἥ', 'E') \
    .replace('Ἦ', 'E') \
    .replace('ἰ', 'i') \
    .replace('ἱ', 'i') \
    .replace('ἳ', 'i') \
    .replace('ἴ', 'i') \
    .replace('ἵ', 'i') \
    .replace('ἶ', 'i') \
    .replace('ἷ', 'i') \
    .replace('Ἰ', 'i') \
    .replace('Ἱ', 'i') \
    .replace('Ἴ', 'i') \
    .replace('Ἵ', 'i') \
    .replace('ὀ', 'o') \
    .replace('ὁ', 'o') \
    .replace('ὂ', 'o') \
    .replace('ὃ', 'o') \
    .replace('ὄ', 'o') \
    .replace('ὅ', 'o') \
    .replace('Ὀ', 'o') \
    .replace('Ὁ', 'o') \
    .replace('Ὃ', 'o') \
    .replace('Ὄ', 'o') \
    .replace('Ὅ', 'o') \
    .replace('ὐ', 'u') \
    .replace('ὑ', 'u') \
    .replace('ὒ', 'u') \
    .replace('ὓ', 'u') \
    .replace('ὔ', 'u') \
    .replace('ὕ', 'u') \
    .replace('ὖ', 'u') \
    .replace('ὗ', 'u') \
    .replace('Ὑ', 'u') \
    .replace('Ὕ', 'u') \
    .replace('Ὗ', 'u') \
    .replace('ὠ', 'O') \
    .replace('ὡ', 'O') \
    .replace('ὢ', 'O') \
    .replace('ὤ', 'O') \
    .replace('ὥ', 'O') \
    .replace('ὦ', 'O') \
    .replace('ὧ', 'O') \
    .replace('Ὡ', 'O') \
    .replace('Ὤ', 'O') \
    .replace('Ὥ', 'O') \
    .replace('Ὦ', 'O') \
    .replace('Ὧ', 'O') \
    .replace('ὰ', 'a') \
    .replace('ὲ', 'e') \
    .replace('ὴ', 'E') \
    .replace('ὶ', 'i') \
    .replace('ὸ', 'o') \
    .replace('ὺ', 'u') \
    .replace('ὼ', 'O') \
    .replace('ᾄ', 'a') \
    .replace('ᾅ', 'a') \
    .replace('ᾐ', 'E') \
    .replace('ᾑ', 'E') \
    .replace('ᾔ', 'E') \
    .replace('ᾖ', 'E') \
    .replace('ᾗ', 'E') \
    .replace('ᾠ', 'O') \
    .replace('ᾧ', 'O') \
    .replace('ᾳ', 'a') \
    .replace('ᾴ', 'a') \
    .replace('ᾶ', 'a') \
    .replace('ᾷ', 'a') \
    .replace('ῃ', 'E') \
    .replace('ῄ', 'E') \
    .replace('ῆ', 'E') \
    .replace('ῇ', 'E') \
    .replace('ῒ', 'i') \
    .replace('ῖ', 'i') \
    .replace('ῢ', 'u') \
    .replace('ῥ', 'r') \
    .replace('ῦ', 'u') \
    .replace('Ῥ', 'r') \
    .replace('ῳ', 'O') \
    .replace('ῴ', 'O') \
    .replace('ῶ', 'O') \
    .replace('ῷ', 'O')

print(text)

